# Generated by Django 5.1.3 on 2024-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
