# Generated by Django 5.1.3 on 2024-11-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
    ]